import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { expect, userEvent, within } from "storybook/test";
import { ActionRow, BottomNavigation, Button, Card, ChoiceCard, EmptyState, FilterChip, IconButton, MediaAttribution, ProgressIndicator, SectionHeader, SelectField, Sheet, StatusBadge, Surface, Tag, TextArea, TextField, Toast } from "@/design-system";

const meta = { title: "Core/Component gallery", parameters: { layout: "padded" } } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

export const ActionsAndStatus: Story = { render: () => <Surface className="ds-story-stack"><SectionHeader title="Core" count="1.1" /><ActionRow><Button>Continuar</Button><Button variant="secondary">Cancelar</Button><Button variant="quiet">Editar</Button><Button variant="danger">Eliminar</Button><Button loading>Guardar</Button><IconButton label="Cerrar">×</IconButton></ActionRow><ActionRow><FilterChip selected>Todos</FilterChip><FilterChip>Comer</FilterChip><FilterChip disabled>Cerrado</FilterChip></ActionRow><ActionRow><StatusBadge status="confirmed">Confirmado</StatusBadge><StatusBadge status="planned">Plan</StatusBadge><StatusBadge status="open">Abierto</StatusBadge><Tag>14:30</Tag></ActionRow><ProgressIndicator current={2} total={3} label="Paso 2 de 3" /></Surface>, play: async ({ canvasElement }) => { const canvas = within(canvasElement); const chip = canvas.getByRole("button", { name: "Comer" }); await userEvent.click(chip); await expect(chip).toHaveAttribute("aria-pressed", "false"); } };
export const FormsAndFeedback: Story = { render: () => <Surface className="ds-story-stack"><TextField label="Nombre" placeholder="Lugar" hint="Usa el nombre público" /><TextField label="Horario" defaultValue="14:30" error="Comprueba el horario" /><TextArea label="Nota" placeholder="Qué quieres recordar" /><SelectField label="Momento" defaultValue="afternoon"><option value="morning">Mañana</option><option value="afternoon">Tarde</option></SelectField><ChoiceCard name="level" value="anchor" selected title="Anchor" description="Compromiso fijo" /><ChoiceCard name="level" value="intention" title="Intención" description="Deseo flexible" /><Toast>Guardado en el día</Toast></Surface> };
export const ContentStates: Story = { render: () => <Surface className="ds-story-stack"><EmptyState title="Aún no hay planes" description="Añade una intención cuando quieras." action={<Button>Añadir plan</Button>} /><div className="ds-story-media"><MediaAttribution author="TRAZA" source="Editorial" license="Uso interno" /></div></Surface> };
export const NavigationAndSurfaces: Story = { render: () => <Surface className="ds-story-screen"><div className="ds-story-stack"><Card><SectionHeader title="Superficie" count="03" /><p>Canvas, raised y navegación comparten tokens.</p></Card></div><BottomNavigation items={[{ id: "journey", label: "Días", icon: "◉" }, { id: "saved", label: "Guardados", icon: "♡" }, { id: "trip", label: "Viaje", icon: "✦" }]} active="journey" onChange={() => undefined} label="Secciones" /></Surface>, parameters: { viewport: { defaultViewport: "mobile402" } } };
export const SheetPattern: Story = { render: () => <div className="ds-story-screen"><Sheet title="Añadir lugar" kicker="Guardados" closeLabel="Cerrar" onClose={() => undefined} footer={<ActionRow><Button variant="secondary">Cancelar</Button><Button>Guardar</Button></ActionRow>}><div className="ds-story-stack"><TextField label="Nombre" defaultValue="Somerset House" /><SelectField label="Estado" defaultValue="saved"><option value="saved">Guardado</option><option value="researching">Investigando</option></SelectField><TextArea label="Nota" /></div></Sheet></div>, parameters: { viewport: { defaultViewport: "mobile402" } } };
