import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { ActionGroup, AssignmentFlow, Button, DayHeader, DayHero, FlightTicketCard, OrganizeToolbar, PageHeader, PlanCard, SavedPlaceCard, SectionHeader, Surface, TripSectionCard } from "@/design-system";
import { ArrowIcon, MapIcon, MoreIcon, PlusIcon } from "@/components/icons";

const meta = { title: "Patterns/Product patterns", parameters: { layout: "padded", viewport: { defaultViewport: "mobile402" } } } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

export const Journey: Story = { render: () => <Surface className="ds-story-screen"><DayHeader date="7 de agosto" position="2 / 8" closeLabel="Cerrar día" onClose={() => undefined} /><DayHero route="Sky Garden → City → Canary Wharf" title="La City desde las alturas. Canary Wharf al anochecer." summary="Sky Garden por la mañana, la City al mediodía y Canary Wharf antes del musical." /><main className="ds-story-stack"><ActionGroup primary={<Button>Añadir plan</Button>} secondary={<Button variant="secondary">Organizar</Button>} /><SectionHeader index="01" title="Mañana" count="1 plan" /><PlanCard time="08:30" title="Sky Garden" meta="Confirmado · City de Londres" status="confirmed" /></main></Surface> };
export const Saved: Story = { render: () => <Surface className="ds-story-stack"><PageHeader eyebrow="Londres 2026" title="Guardados" count="28 lugares" /><SavedPlaceCard title="Hard Rock Cafe" category="Comer y beber" area="Mayfair" tags={["Restaurante", "Música", "Cabina de One Direction"]} onAssign={() => undefined} mapsHref="https://maps.google.com" onDetail={() => undefined} onEdit={() => undefined} assignIcon={<PlusIcon />} assignEndIcon={<ArrowIcon />} mapsIcon={<MapIcon />} moreIcon={<MoreIcon />} /><SavedPlaceCard title="M&M’s London" category="Compras" area="Leicester Square" tags={["Tienda", "Dulces"]} assignedLabel="Asignado al 7 de agosto" onAssign={() => undefined} mapsHref="https://maps.google.com" onDetail={() => undefined} onEdit={() => undefined} assignIcon={<PlusIcon />} assignEndIcon={<ArrowIcon />} mapsIcon={<MapIcon />} moreIcon={<MoreIcon />} /></Surface> };
export const Trip: Story = { render: () => <Surface className="ds-story-stack"><TripSectionCard index="01 · Vuelos" title="Ida y vuelta" className="travel-doc--flight"><FlightTicketCard origin="Sevilla · SVQ" destination="Londres · LGW" startTime="11:50" endTime="13:35" meta="6 ago · BA2649" /></TripSectionCard><TripSectionCard index="02 · Alojamiento" title="Ibis Styles London Ealing"><p>Base del viaje en Londres</p></TripSectionCard></Surface> };
export const Assignment: Story = { render: () => <Surface className="ds-story-stack"><AssignmentFlow step={1} total={2} title="¿En qué día?" next={() => undefined}><Button variant="secondary">Viernes 07</Button><Button variant="secondary">Sábado 08</Button></AssignmentFlow></Surface> };
export const Organize: Story = { render: () => <Surface className="ds-story-screen"><div className="ds-story-spacer">Reordena sin perder anchors.</div><OrganizeToolbar count={2} onCancel={() => undefined} onSave={() => undefined} /></Surface> };
